app/urls.py
from django.urls import path
from .views import app_index, app_welcome, app_dashboard, app_spec, app_saloon, app_clients, app_service, app_temp_sh, app_report, app_cale, app_shed, app_agent, app_product

urlpatterns = [
    path('', app_index.load, name="app_index"),
    path('welcome/<str:pk>', app_welcome.load, name="app_welcome"),
    path('dashboard', app_dashboard.load, name="app_dashboard"),
    
    
    path('service', app_service.load, name="app_service"),
    path('service_filter', app_service.filter, name="app_service_filter"),
    path('service_add', app_service.add, name="app_service_add"),
    path('service_close', app_service.filter, name="app_service_close"),
    path('service_save/<str:pk>', app_service.save, name="app_service_save"),
    path('service_edit/<str:pk>', app_service.edit, name="app_service_edit"),
    path('service_delete/<str:pk>', app_service.delete, name="app_service_delete"),
    path('service_page/<str:page>', app_service.page, name='app_service_page'),
    
    path('spec', app_spec.load, name="app_spec"),
    path('spec_filter', app_spec.filter, name="app_spec_filter"),
    path('spec_add', app_spec.add, name="app_spec_add"),
    path('spec_close', app_spec.filter, name="app_spec_close"),
    path('spec_save/<str:pk>', app_spec.save, name="app_spec_save"),
    path('spec_edit/<str:pk>', app_spec.edit, name="app_spec_edit"),
    path('spec_delete/<str:pk>', app_spec.delete, name="app_spec_delete"),
    path('spec_page/<str:page>', app_spec.page, name='app_spec_page'),
    
    path('clients', app_clients.load, name="app_clients"),
    path('clients_filter', app_clients.filter, name="app_clients_filter"),
    path('clients_add', app_clients.add, name="app_clients_add"),
    path('clients_close', app_clients.filter, name="app_clients_close"),
    path('clients_save/<str:pk>', app_clients.save, name="app_clients_save"),
    path('clients_edit/<str:pk>', app_clients.edit, name="app_clients_edit"),
    path('clients_delete/<str:pk>', app_clients.delete, name="app_clients_delete"),
    path('clients_page/<str:page>', app_clients.page, name='app_clients_page'),
    
    path('saloon', app_saloon.load, name="app_saloon"),
    path('saloon_filter', app_saloon.filter, name="app_saloon_filter"),
    path('saloon_add', app_saloon.add, name="app_saloon_add"),
    path('saloon_close', app_saloon.close, name="app_saloon_close"),
    path('saloon_save/<str:pk>', app_saloon.save, name="app_saloon_save"),
    path('saloon_edit/<str:pk>', app_saloon.edit, name="app_saloon_edit"),
    path('saloon_delete/<str:pk>', app_saloon.delete, name="app_saloon_delete"),
    path('saloon_page/<str:page>', app_saloon.page, name='app_saloon_page'),
    path('saloon_active/<str:pk>', app_saloon.active, name='app_saloon_active'),
    
    
    path('report', app_report.load, name="app_report"),
    
    path('cale', app_cale.load, name="app_cale"),
    path('cale_next_month/<str:month>/<str:year>', app_cale.next_month, name="app_cale_next_month"),
    path('cale_prev_month/<str:month>/<str:year>', app_cale.prev_month, name="app_cale_prev_month"),
    path('cale_add/<str:day>/<str:month>/<str:year>', app_cale.add, name="app_cale_add"),
    path('cale_close', app_cale.close, name="app_cale_close"),
    path('cale_edit/<str:pk>/<str:day>/<str:month>/<str:year>', app_cale.edit, name='app_cale_edit'),
    path('cale_delete/<str:pk>/<str:day>/<str:month>/<str:year>', app_cale.delete, name='app_cale_delete'),
    path('cale_save/<str:pk>/<str:day>/<str:month>/<str:year>', app_cale.save, name="app_cale_save"),
    path('cale_date/<str:day>/<str:month>/<str:year>', app_cale.select_date, name="app_cale_date"),
    path('cale_spec/<str:day>/<str:month>/<str:year>/<str:spec_id>', app_cale.select_spec, name="app_cale_spec"),
    
    path('shed', app_shed.load, name="app_shed"),
    path('shed_next_month/<str:month>/<str:year>', app_shed.next_month, name="app_shed_next_month"),
    path('shed_prev_month/<str:month>/<str:year>', app_shed.prev_month, name="app_shed_prev_month"),
    path('shed_add/<str:day>/<str:month>/<str:year>', app_shed.add, name="app_shed_add"),
    path('shed_close/<str:day>/<str:month>/<str:year>', app_shed.close, name="app_shed_close"),
    path('shed_date/<str:day>/<str:month>/<str:year>', app_shed.select_date, name="app_shed_date"),
    path('shed_spec/<str:day>/<str:month>/<str:year>/<str:spec_id>', app_shed.select_spec, name="app_shed_spec"),    
    path('meet_add/<str:day>/<str:month>/<str:year>/<str:hour>/<str:minute>/<str:meet_id>', app_shed.meet_add, name='app_meet_add'),
    path('meet_edit/<str:day>/<str:month>/<str:year>/<str:hour>/<str:minute>/<str:meet_id>', app_shed.meet_edit, name='app_meet_edit'),    
    path('meet_save/<str:day>/<str:month>/<str:year>/<str:meet_id>', app_shed.meet_save, name='app_meet_save'),
    path('meet_del/<str:day>/<str:month>/<str:year>/<str:meet_id>', app_shed.meet_del, name='app_meet_del'),
    
    path('meet_postpone/<str:day>/<str:month>/<str:year>/<str:meet_id>', app_shed.meet_postpone, name='app_meet_postpone'),
    
    path('postpone_close/<str:day>/<str:month>/<str:year>', app_shed.postpone_close, name='app_postpone_close'),
    path('postpone_spec', app_shed.postpone_spec, name='app_postpone_spec'),
    path('postpone_time', app_shed.postpone_time, name='app_postpone_time'),
    path('postpone_save/<str:day>/<str:month>/<str:year>/<str:meet_id>', app_shed.postpone_save, name='app_postpone_save'),
    
    path('agent', app_agent.load, name="app_agent"),
    path('agent_filter', app_agent.filter, name="app_agent_filter"),
    path('agent_add', app_agent.add, name="app_agent_add"),
    path('agent_close', app_agent.filter, name="app_agent_close"),
    path('agent_save/<str:pk>', app_agent.save, name="app_agent_save"),
    path('agent_edit/<str:pk>', app_agent.edit, name="app_agent_edit"),
    path('agent_delete/<str:pk>', app_agent.delete, name="app_agent_delete"),
    path('agent_page/<str:page>', app_agent.page, name="app_agent_page"),
    
    path('product/<str:category>', app_product.load, name="app_product"),
    path('product_filter/<str:category>', app_product.filter, name="app_product_filter"),
    path('product_add/<str:category>', app_product.add, name="app_product_add"),
    path('product_save/<str:pk>/<str:category>', app_product.save, name="app_product_save"),
    path('product_edit/<str:pk>/<str:category>', app_product.edit, name="app_product_edit"),
    path('product_close/<str:category>', app_product.filter, name="app_product_close"),
    path('product_delete/<str:pk>/<str:category>', app_product.delete, name="app_product_delete"),
    path('product_page/<str:page>/<str:category>', app_product.page, name="app_product_page"),
    
    path('sh_template', app_temp_sh.load, name='app_sh_template'),
    path('_sh_temp_add', app_temp_sh.add, name='app_sh_template_add'),
    path('_sh_temp_upd/<str:pk>', app_temp_sh.update, name='app_sh_template_upd'),
]

crm/urls.py

from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('app', include('app.urls')),
]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator


class Firm(models.Model):
    CURRENCYS = {
        "USD": "$ USD",
        "EUR": "€ EUR",
        "UAH": "₴ UAH",
    }
    
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=40)
    note = models.TextField(null=True, blank=True)
    mail = models.EmailField()
    phone = models.CharField(max_length=15)
    person = models.CharField(max_length=100)
    tested = models.BooleanField(default=False)
    bank = models.CharField(max_length=240, null=True, blank=True)
    currency = models.CharField(max_length=3, choices=CURRENCYS, default="UAH")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Client(models.Model):
    id = models.BigAutoField(primary_key=True)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE)
    f_name = models.CharField(max_length=40, null=False)
    l_name = models.CharField(max_length=40, null=True, blank=True)
    phone = models.CharField(max_length=12, null=False)
    telegram = models.CharField(max_length=30, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['l_name', 'f_name']

    def __str__(self):
        name = self.f_name
        if self.l_name:
            name = name + " " + self.l_name 
        return name

class Service(models.Model):
    id = models.BigAutoField(primary_key=True)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE)
    name = models.CharField(max_length=40, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(limit_value=0.009, message="Ціна має бути більше 0")])
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['name']

    def __str__(self):
        return self.name


class SpecModel(models.Model):
    id = models.BigAutoField(primary_key=True)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE)
    spec_fname = models.CharField(max_length=30, null=False)
    spec_lname = models.CharField(max_length=30, null=False)
    spec_phone = models.CharField(max_length=12, null=True, blank=True)
    spec_color = models.CharField(max_length=10, null=False)
    spec_active = models.BooleanField(null=False, default=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['spec_active','spec_fname']

    def __str__(self):
        return self.spec_fname + " " + self.spec_lname
    
    @property
    def full_name(self):
        return self.spec_fname + " " + self.spec_lname
    
    # @property
    # def countCal(self):
    #     return CalendarModel.objects.filter(cl_spec=self.id).count()
    
    

class SaloonModel(models.Model):
    id = models.BigAutoField(primary_key=True)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE)
    sln_name = models.CharField(max_length=50, null=False)
    sln_address = models.CharField(max_length=150, null=True, blank=True)
    sln_phone = models.CharField(max_length=12, null=True, blank=True)
    sln_note = models.TextField(null=True, blank=True)
    sln_color = models.CharField(max_length=10, null=False, default="#FFFFFF")
    sln_main = models.BooleanField(null=False, default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['sln_name']

    def __str__(self):
        return self.sln_name
    
class mSheduleTemplate(models.Model):
    id = models.BigAutoField(primary_key=True)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE, null=False)
    st_name = models.CharField(max_length=40, null=False)
    st_template = models.CharField(max_length=250, null=False)
    st_note = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['st_name']
    
    def __str__(self) -> str:
        return self.st_name

class CalendarModel(models.Model):
    id = models.BigAutoField(primary_key=True)
    cl_date = models.DateField(null=False)
    cl_saloon = models.ForeignKey(SaloonModel, on_delete=models.CASCADE)
    cl_spec = models.ForeignKey(SpecModel, on_delete=models.SET_NULL, null=True)
    cl_shed = models.ForeignKey(mSheduleTemplate, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['id']
        
    def __str__(self) -> str:
        return self.cl_date.isoformat()
    
class mMeet(models.Model):
    class StatusList(models.IntegerChoices):
        REG = 10
        DONE = 11
        CANC = 12
        PAID = 13
        BOT_REG = 20
        BOT_DONE = 21
        BOT_CANC = 22
        BOT_PAID = 23
        API = 30
        API_DONE = 31
        API_CANC = 32
        API_PAID = 33
    
    id = models.BigAutoField(primary_key=True)
    m_dt = models.DateTimeField(null=False)
    m_saloon = models.ForeignKey(SaloonModel, on_delete=models.CASCADE, null=False, related_name='saloon')
    m_spec = models.ForeignKey(SpecModel, on_delete=models.SET_NULL, null=True, related_name='spec')
    m_client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, related_name='client')
    m_service = models.CharField(max_length=250, null=True, blank=True)
    m_note = models.TextField(null=True, blank=True)
    # * запасное поле
    m_report = models.TextField(null=True, blank=True)
    
    m_status = models.IntegerField(choices=StatusList, default=StatusList.REG)
    m_rating = models.IntegerField(default=0)
    m_review = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    update = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['m_dt']
    
    def __str__(self) -> str:
        return self.m_dt.isoformat()
    
class mProducts(models.Model):
    class CategoryList(models.IntegerChoices):
        Product = 1, ("Товар")
        Material = 2, ("Матеріал")
                
    class UnitsList(models.IntegerChoices):
        Pcs = 1, ("шт")
        Gramm = 2, ("г")
        Liter = 3, ("л")
        Meter = 4, ("м")
    
    id = models.BigAutoField(primary_key=True)
    category = models.IntegerField(choices=CategoryList, default=CategoryList.Product)
    p_code = models.CharField(max_length=40, null=True, blank=True)
    p_name = models.CharField(max_length=40, null=False, validators=[MinLengthValidator(2, "Назва має бути більше 2 символів"),])
    p_note = models.CharField(max_length=250, null=True, blank=True)
    p_unit = models.IntegerField(choices=UnitsList, default=UnitsList.Pcs)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    update = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['category', 'p_name']
    
    def __str__(self) -> str:
        return self.p_name
    
    


class mCheck(models.Model):
    id = models.BigAutoField(primary_key=True)
    meet = models.ForeignKey(mMeet, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(mProducts, on_delete=models.SET_NULL, null=True)
    c_price = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    update = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['id']
        
    def __str__(self) -> str:
        return str(self.id)
    
class mAgent(models.Model):
    id = models.BigAutoField(primary_key=True)
    a_code = models.CharField(max_length=40)
    a_name = models.CharField(max_length=40)
    a_note = models.TextField(null=True, blank=True)
    a_mail = models.EmailField(null=True, blank=True)
    a_phone = models.CharField(max_length=15, null=True, blank=True)
    a_person = models.CharField(max_length=100, null=True, blank=True)
    a_bank = models.CharField(max_length=240, null=True, blank=True)
    firm = models.ForeignKey(Firm, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['a_name', 'a_code']

    def __str__(self):
        return self.a_name
    
class mDocument(models.Model):
    class DoctypeList(models.IntegerChoices):
        PND = 1, ("Прибуткова накладна")        
        OND = 20, ("Видаткова накладна")
    
    id = models.BigAutoField(primary_key=True)
    d_type = models.IntegerField(choices=DoctypeList, default=DoctypeList.PND)
    d_num = models.CharField(max_length=40, null=True, blank=True)
    d_date = models.DateTimeField(null=False)
    d_note = models.CharField(max_length=150, null=True, blank=True)
    d_file = models.FileField(upload_to='uploads/')
    agent = models.ForeignKey(mAgent, on_delete=models.SET_NULL, null=True)
    saloon = models.ForeignKey(SaloonModel, on_delete=models.CASCADE)

app/templates/app_product/app_product_container.html

<div class="page-container mt-3">
    
    {% include 'app_product/app_product_form.html' %}

    <div id="agent-table" class="{% if form %} visually-hidden {% endif %}">

        <div class="overflow-auto" id="spec-table">
            <table class="table table-hover table-sm">
                <thead>
                    <tr>
                        {% comment %} <th scope="col">#</th> {% endcomment %}
                        <th scope="col">Артикул</th>
                        <th scope="col">Назва</th>
                        <th scope="col">Кількість</th>                    
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>        
                <tbody id="data_agent">
                    {% include 'app_product/app_product_row.html' %}      
                </tbody>  
            </table>
        </div>

        {% if pag %}
        <div class="btn-group mt-3" role="group" aria-label="pagination">
            {% for  page in pag %}
                {% if page == apage %}
                    <button type="button" 
                                class="btn btn-sm btn-primary"
                                hx-post="{% url 'app_product_page' page category %}"
                                hx-trigger="click"
                                hx-target=".page-container"
                                hx-swap="outerHTML">{{page}}</button>
                {% else %}
                    <button type="button" 
                    class="btn btn-sm"
                    hx-post="{% url 'app_product_page' page category %}"
                    hx-trigger="click"
                    hx-target=".page-container"
                    hx-swap="outerHTML">{{page}}</button>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

    </div>
</div>

app/templates/app_product/app_product_form.html
<div class=" mt-3 mb-3 {% if not form %} visually-hidden {% endif %}"  id="form-widget">
    <div class="shadow p-3 mb-5 bg-body-tertiary col-xl-8 m-auto">
        <form action="" class="form-client" method="POST">
            {% csrf_token %}
            <div class="form-content container">
                <div class="row mb-3">
                    <div class="col-3">
                        <label class="form-label-sm" for="p-code">Артикул</label>
                        {{form.p_code}}
                    </div>
                    <div class="col-7">
                        <label class="form-label-sm" for="p-name">Назва</label>
                        {{form.p_name}}
                    </div>
                    <div class="col-2">
                        <label class="form-label-sm" for="p-unit">Од. виміру</label>
                        {{form.p_unit}}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-12">
                        <label class="form-label-sm" for="p-note">Нотатки</label>
                        {{form.p_note}}
                    </div>
                </div>
                <div class="row justify-content-end">
                    <div class="btn-group col-2" role="group" aria-label="Basic mixed styles example">

                        <button type="button" class="btn btn-success" id="fw-but-save"
                            hx-post="{% url 'app_product_save' id category %}" hx-trigger="click" hx-target=".page-container"
                            hx-swap="outerHTML">Зберегти</button>

                        <button type="button" class="btn btn-warning btn-sm" id="fw-but-close"
                            hx-post="{% url 'app_product_close' category %}" hx-trigger="click" hx-target=".page-container"
                            hx-swap="outerHTML">
                            <i class="bi bi-x-lg"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    {% if errors %}
    <div class="shadow p-3 mb-5 bg-body-tertiary col-xl-8 m-auto alert-danger" role="alert">        
        {% for message in errors %}
        <span style="color:#dc3545;" class="mx-3"><i class="bi bi-exclamation-triangle-fill"></i></span><span>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}
    
</div>

app/templates/app_product/app_product_row.html
{% for data in product_data %}

    {% comment %} <th class="num" scope="row"></th> {% endcomment %}
    <td class="col-2">{{data.p_code|default_if_none:""}}</td>
    <td class="col-7">{{data.p_name}}</td>
    {% comment %} <td class="col-3">{{data._units}}</td> {% endcomment %}
    <td class="col-3">{{data.get_p_unit_display}}</td>
    
    <td class="col p-0">            
        <div 
            class="btn btn-sm"             
            type="button" 
            id="tb-but-edit" 
            hx-post="{% url 'app_product_edit' data.id category %}"
            hx-trigger="click"
            hx-target=".page-container"
            hx-swap="outerHTML">
            <i class="bi bi-pencil"></i>
        </div>
    </td>
    <td class="col p-0">
        <button 
            class="btn btn-sm btn-outline-light text-danger"             
            type="button" 
            id="tb-but-del" 
            hx-post="{% url 'app_product_delete' data.id category %}"
            hx-trigger="click"
            hx-target=".page-container"
            hx-swap="outerHTML"
            {% if data.docs %} disabled {% endif %}>
            <i class="bi bi-trash3"></i>
        </button>
        
    </td>
</tr>
{% endfor %}